### ISSUE TITLE
CentOS 能安装不？

### ISSUE THREAD

**Issue by HTMLtargetblank** [yvbbrjdr/pipesocks#15]

**Comment by yvbbrjdr** [comment]
@CoderJin 可以的 看这里：https://pipesocks.github.io/md/tutorial#linux-1 只是可能会遇到glibc版本太低无法运行的问题 百度一下更新个glibc版本就行了

**Comment by yvbbrjdr** [comment]
@CoderJin 有任何疑问的话 欢迎到这里来https://t.me/pipesocks
