### ISSUE TITLE
为何提示pipesocks: not found？

### ISSUE THREAD

**Issue by luckypoem** [yvbbrjdr/pipesocks#16]
hi.

root@AR:\~/pipesocks# ./runpipesocks.sh pump -p 7344 -k mypassword
./runpipesocks.sh: 10: ./runpipesocks.sh: /root/pipesocks/./pipesocks: not found
root@AR:\~/pipesocks# ls
libQt5Core.so.5     libicui18n.so.56  pipesocks
libQt5Network.so.5  libicuuc.so.56    platforms
libicudata.so.56    libsodium.so.18   runpipesocks.sh
root@AR:\~/pipesocks#

明明存在可执行文件 pipesocks

**Comment by yvbbrjdr** [comment]
This is not reasonable. See if you can run `./pipesocks` in this folder. Show me the error info.

**Comment by luckypoem** [comment]
hi.

root@AR:~/pipesocks# ls
libQt5Core.so.5     libicui18n.so.56  pipesocks
libQt5Network.so.5  libicuuc.so.56    platforms
libicudata.so.56    libsodium.so.18   runpipesocks.sh
root@AR:~/pipesocks# ./pipesocks
-bash: ./pipesocks: No such file or directory
root@AR:~/pipesocks# 

真是匪夷所思。我这个vps是openvz vps.在另外一个vps(kvm vps)上，没有问题。
难道是openvz虚拟化技术造成了问题？

**Comment by yvbbrjdr** [comment]
@luckypoem 这没法解释啊。。。好端端的一个文件不存在。。

**Comment by luckypoem** [comment]
hi.

root@AR:\~/pipesocks/pipesocks# apt-get -y install qt5-default qt5-qmake
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package qt5-default
E: Unable to locate package qt5-qmake
root@AR:\~/pipesocks/pipesocks# 
root@AR:\~/pipesocks/pipesocks# cat /etc/issue.net
Debian GNU/Linux 7
root@AR:\~/pipesocks/pipesocks#

我的系统是Debian 7，没有qt5-default 、qt5-qmake这2个包，怎么办？

**Comment by yvbbrjdr** [comment]
@luckypoem 还是用docker吧。。。pipesocks/pipesocks:latest

**Comment by yvbbrjdr** [comment]
@luckypoem 你的系统把存在的文件说成不存在也是很神奇 要不要谷歌一下？

**Comment by luckypoem** [comment]
但是我的这个vps是openvz vps,内核太低，又升不了级，没法安装docker.

**Comment by luckypoem** [comment]
我去http://stackoverflow.com/问一问

**Comment by luckypoem** [comment]
hi.

有答复了：http://stackoverflow.com/questions/42580903/why-it-exports-pipesocks-no-such-file-or-directory-actually-the-file-pipe ，但还是不行：
root@AR:~/pipesocks# LD_LIBRARY_PATH=. ./pipesocks
-bash: ./pipesocks: No such file or directory
root@AR:~/pipesocks# ldconfig
root@AR:~/pipesocks# ./pipesocks
-bash: ./pipesocks: No such file or directory
root@AR:~/pipesocks#

**Comment by yvbbrjdr** [comment]
@luckypoem 实际上runpipesocks.sh里面有这一行。。所以原因出在还缺其他库。。。。？

**Comment by bdbai** [comment]
```sh
file pipesocks
ldd pipesocks
stat pipesocks
```
分别输出什么？

**Comment by luckypoem** [comment]
我看到这里http://stackoverflow.com/questions/2716702/no-such-file-or-directory-error-when-executing-a-binary?rq=1 说：“You get this error when you try to run a 32-bit build on your 64-bit Linux. ”，这个可能是原因。我现在这个openvz vps是32位的，而 KVM vps是64位的，我下载的https://github.com/pipesocks/pipesocks/releases/download/2.3/pipesocks-2.3-linux.tar.xz这个包是64位系统下打的包吧？

root@AR:~/pipesocks# file pipesocks
pipesocks: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0x359797c67a319712e9fa7695d2e07bd262603dfc, not stripped
root@AR:~/pipesocks#

这证实了你这个tar.xz文件包确实是64位系统下打的包，可否提供32位系统下打的包呢？

**Comment by yvbbrjdr** [comment]
@luckypoem 非常抱歉。。。Qt不提供32位版本 所以我没有办法编译32位的文件 浪费您的时间了

**Comment by luckypoem** [comment]
哦。那就在https://pipesocks.github.io/md/tutorial ,强调linux vps必须为64位系统。可用uname -a查看。

**Comment by yvbbrjdr** [comment]
@luckypoem 事实上。。你可以去看https

**Comment by yvbbrjdr** [comment]
@luckypoem 事实上。。要求在这里。。。https://pipesocks.github.io/index-cn.html#download

**Comment by yvbbrjdr** [comment]
Anyway, 谢谢你付出的努力

**Comment by luckypoem** [comment]
@bdbai 
pipesocks在ios上，还没有上架啊？都一个多月了。
要是哪天上架了，麻烦在此通知一声。
非常感谢

**Comment by bdbai** [comment]
@luckypoem
作者大大表示不再用 tg 了，现在应该在忙个人的事情。
我记得他说九月上架的。耐心等等吧。

**Comment by yvbbrjdr** [comment]
在准备签证 这段时间不准备碰敏感的东西 抱歉
