### ISSUE TITLE
可能我的姿势不对

### ISSUE THREAD

**Issue by usagiryu** [yvbbrjdr/pipesocks#22]
配置了日本的vultr
然后 mac端
![](https://p1.bqimg.com/519918/629b6e28c6ef926a.png)
![](https://p1.bqimg.com/519918/350a0dc15d4b98d0.png)
![](https://p1.bqimg.com/519918/1745164cbb547696.png)

**Comment by yvbbrjdr** [comment]
Ping is useless in testing pipesocks because it does not support ICMP.
It seems that you haven't successfully launched your server. Just show me your server log.

**Comment by usagiryu** [comment]
找到问题了，学校设置了防火墙白名单，只允许80和443，可能是这个问题

**Comment by yvbbrjdr** [comment]
看来是你学校姿势不对😂

**Comment by usagiryu** [comment]
惨无人道的封锁了22

**Comment by yvbbrjdr** [comment]
真是😂简直断掉了所有游戏

**Comment by usagiryu** [comment]
是的而且不定期封锁微信图片服务器，文字和语音发的出去，图片就是发不出去
