### ISSUE TITLE
winserve2012上停止运行

### ISSUE THREAD

**Issue by bert97** [yvbbrjdr/pipesocks#23]
如题，没法运行，兼容模式也不行，

**Comment by yvbbrjdr** [comment]
If you can't boot up GUI under Windows, you can try running it in the background with cmd.

Open a cmd, cd to the directory containing pipesocks, and then enter "pipesocks.exe pump -p port -k password > pipesocks.log" (replace the port and password with your choice). (Actually, this is the command for pump, you can find other commands right [here](https://github.com/pipesocks/pipesocks#command-line-interface)) Nothing will happen then but you can confirm that pipesocks is running with task manager, and you can also see the log in the file "pipesocks.log".

Reply if you have further questions.
