### ISSUE TITLE
Pipesocks won't run properly on win7

### ISSUE THREAD

**Issue by Choutouketsu** [yvbbrjdr/pipesocks#27]
Hello, the pipesocks won't work on win7 even after I chose comparability for Windows XP

**Comment by Choutouketsu** [comment]
I am wondering if I need prepare some environment on win7 before I run this software? thanks

**Comment by yvbbrjdr** [comment]
Which error have you encountered?

**Comment by Choutouketsu** [comment]
![1](https://user-images.githubusercontent.com/24585116/30032230-357708d6-91c7-11e7-9a21-1f2032d42fcb.PNG)
Hello look, it means "the software has stopped work"
Should I download some library?

**Comment by Choutouketsu** [comment]
@yvbbrjdr

**Comment by yvbbrjdr** [comment]
If I don’t know the details of why it stopped working, I can’t do anything, because pipesocks runs properly on Windows 7 on my computer without additinal libraries. (Actually it is compiled on a clean Windows 7 x86 system)

**Comment by yvbbrjdr** [comment]
Maybe check with your graphic card driver to see if it supports OpenGL 2.0.

**Comment by Choutouketsu** [comment]
@yvbbrjdr Hello, this time i tried another computer, and it still stopped upon i double click on the pipesocks.exe file. I did nothing to it. How should I report details the error? My OS is Win7 64 bit. Is this a big cause?    :)

**Comment by yvbbrjdr** [comment]
Actually I have stopped maintaining this program. My suggestion would be recommending you to upgrade your system.

**Comment by Choutouketsu** [comment]
oh, what a big pity. Anyway, thank you. I would love to upgrade, but I guess may be x86 would work. I will try using some 32 bit win7 first. Besides shadowsocks work well at present. I need dig more ways to keep myself updated before the GFW have bigger move. thanks again.

**Comment by yvbbrjdr** [comment]
Haha, sorry. Just treat pipesocks as an alternative way to bypass the wall in case other softwares don't work in the future.

**Comment by Choutouketsu** [comment]
And you are my hero, good luck!
