### ISSUE TITLE
请问如何用GFWlist pac来分流代理？

### ISSUE THREAD

**Issue by loveproe** [yvbbrjdr/pipesocks#28]
我在linux运行tap,提示GFWList not retrieved。请问用什么文件名，他才能识别gfw列表？

我在win10运行，dump出来的log也是同样的GFWList not retrieved
[2017-10-13 15:45:44] 192.168.1.231:57062 failed to get GFWList PAC

**Comment by yvbbrjdr** [comment]
应该是你本地 OpenSSL 的问题 或者是 GitHub User Content 被墙的缘故。
建议你用 Chrome 的插件 SwitchyOmega 去做 GFWList。

**Comment by loveproe** [comment]
我在路由器用全局代理，提示还是同样，不能得到GFWlist，能否增加读取一个本地gfwlist文件选项？否则只能做一个sock5全局代理，手机不是很方便。
不过还是谢谢了。如果没办法，只能用Pipesocks做中转。
